services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U payload']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: node:24.13.1
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm ci && npm run build && npm start"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://payload:payload@db:5432/payload
      - PAYLOAD_SECRET=your-secret-key-change-this
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
